### ISSUE TITLE
Form Input dan edit data Usulan RAD Notifikasi sukses terlalu cepat hilang

### ISSUE THREAD

**Issue by indrijunanda** [hendrasenpai/pks#1]
di form input usulan RAD notifikasi pemberitahuan terlalu cepat hilang, mohon  bantuannya kk :v

**Comment by bondanchuk** [comment]
Oke nanti aku coba, itu di controller apa?

**Comment by indrijunanda** [comment]
di controller Usulanrad, tp itu ada yg aku bedain sedikit, agak bingung nulis di modelnya :v

**Comment by bondanchuk** [comment]
fix
